version: "3.9"

services:
  redis:
    image: 'redis:7-alpine'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - 'redis_data:/data'
    restart: unless-stopped

  wa-api:
    build: .
    container_name: wa-api
    env_file:
      - .env
    expose:
      - "3000"  # internal port only
    volumes:
      - './auth:/app/auth'
      - './uploads:/app/uploads'
      - './data:/data'
    depends_on:
      - redis
    restart: unless-stopped
    labels:
      - coolify.managed=true

    # Caddy basic auth configuration
    environment:
      SERVICE_NAME: wa-api
      SERVICE_PORT: 3000
      CADDY_BASIC_AUTH: "${WA_API_USER}:${WA_API_PASSWORD}"  # will enable basic auth on your domain

volumes:
  redis_data:
    name: redis_data
